### ISSUE TITLE
Automated model download

### ISSUE THREAD

**Issue by mcoughlin** [nuclear-multimessenger-astronomy/nmma#104]
We should upload the large model files to Zenodo and enable their on-demand download as necessary.

**Comment by Theodlz** [comment]
Hi @mcoughlin, I'll start by uploading one model and writing some code to fetch it

**Comment by sahiljhawar** [comment]
Maybe use [GitHub LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage). Process will be more streamlined.

**Comment by mcoughlin** [comment]
We should definitely do that for the other large files. The Zenodo download stuff seems to be working ok for the moment.

**Comment by mcoughlin** [comment]
Closing given that Zenodo seems good.
