### ISSUE TITLE
Early time lightcurve generation disparity

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#106]
While working on an NMMA adjacent project, I found that there may be a disparity in the generated EM observations at early times (values less than 1 day) depending on the method used to generate the lightcurve. Specifically, I found a disparity between the lightcurves generated when calling light_curve_generation and those generated by the best fit parameters and calling the NMMA lightcurve model functions directly in a python script. Investigating this further, I found that there may be a disparity between the two methods of lightcurve generation (command line vs script) even when using the exact same parameter values from the same injection file.

**Comment by mcoughlin** [comment]
@tylerbarna Closing this assuming that unit test solves it. Feel free to reopen if not.
