### ISSUE TITLE
End of Line

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#118]
Do we use LF or CRLF for nmma? I know Unix traditionally uses LF and Windows uses CRLF, but I'm not sure what's the standard for MacOS, since most people working on the project use MacOS

**Comment by tylerbarna** [comment]
Along the same line of thinking, would it be worth having a .gitattributes file?

**Comment by mcoughlin** [comment]
@tylerbarna Let's default to UNIX. and I agree that .gitattributes would be nice
