### ISSUE TITLE
Error when training new model because it is not yet on Zenodo

### ISSUE THREAD

**Issue by bfhealy** [nuclear-multimessenger-astronomy/nmma#123]
When training a new model that is not yet on Zenodo, training finishes and the model is saved locally. But before making the final plot, the `nmma.utils.models.get_model` function is called and states that it will try local files. It then returns an empty list: https://github.com/nuclear-multimessenger-astronomy/nmma/blob/668dd0bb800a0c25ee1cb07c29c5d4c638ff947b/nmma/utils/models.py#L176 raising the following error, even though the model is saved locally:
```
Bu2019lm_tf not on Zenodo, trying local files
Traceback (most recent call last):
  File "/Users/bhealy/miniforge3/envs/nmma_env/bin/create_svdmodel", line 33, in <module>
    sys.exit(load_entry_point('nmma==0.0.8', 'console_scripts', 'create_svdmodel')())
  File "/Users/bhealy/nmma/nmma/em/create_svdmodel.py", line 223, in main
    light_curve_model = SVDLightCurveModel(
  File "/Users/bhealy/nmma/nmma/em/model.py", line 244, in __init__
    _, model_filters = get_model(
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by mcoughlin** [comment]
@bfhealy any obvious quick fixes?

**Comment by bfhealy** [comment]
@mcoughlin  I think making this call to `get_model` conditional may do the trick. I'll open a PR:

https://github.com/nuclear-multimessenger-astronomy/nmma/blob/668dd0bb800a0c25ee1cb07c29c5d4c638ff947b/nmma/em/model.py#L244C18-L244C18

```
if self.model is None:
                _, model_filters = get_model(
                    self.svd_path, f"{self.model}_tf", filters=filters
                )
```

**Comment by bfhealy** [comment]
Although I see that `self.model` is used in the call to `get_model`... perhaps a different condition.
