### ISSUE TITLE
Zenodo when running in mpiexec with multiple cores

### ISSUE THREAD

**Issue by mcoughlin** [nuclear-multimessenger-astronomy/nmma#126]
On large clusters, it is common to what to run mpiexec -np 18 light_curve_analysis ... which attempts to trigger the Zenodo download 18 times, rather than start it once in one thread and block until completion. It would be nice to add some code where one thread starts the download and assigns some kind of temporary file that the other threads wait til are removed before continuing onwards.

**Comment by Theodlz** [comment]
Hi @mcoughlin, not possible to just trigger the download separately (I can make it so the utils/models.py has an argparse) before running that command? That seems very reasonable.

**Comment by mcoughlin** [comment]
@Theodlz Yes that would be fine. Some example command line with just the model name and svdpath or similar which just downloads sounds like a good way.

**Comment by mcoughlin** [comment]
Closing assuming that the download script is sufficient for this.
