### ISSUE TITLE
Fortran file name limitation

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#141]
Because Fortran underpins some of the tools used by NMMA, issues can come up when trying to do analysis of files with longer paths/filenames. If the path string is long enough, Fortran will break. Not sure if our code is low enough level to allow for this, but some method for temporary relative pathing might alleviate the edge-case issue.

**Comment by sahiljhawar** [comment]
I think the issue I was facing maybe related to this. My issue was, if the output directory name is longer than certain length then the files which are supposed to be created inside that fails, however the data is being writtened on the file but the name  of the file is messed up. for example, the name of the `post_equal_weights.dat` will be `post_equal_weights.da` or `post_equal_weights`. Is this the same type of issue you faced?

**Comment by mcoughlin** [comment]
@sahiljhawar Could you open a quick PR along the lines of https://github.com/mcoughlin/gwemlightcurves/blob/master/gwemlightcurves/lightcurve_utils.py#L513 
to deal with this? It is a known issue with MultiNest.

**Comment by sahiljhawar** [comment]
@mcoughlin Yes, @tsunhopang told me about this issue.

**Comment by sahiljhawar** [comment]
@mcoughlin I didn't get it. What exactly needs to be done? :')

**Comment by mcoughlin** [comment]
Modify whatever line tries to find post_equal_weights.dat to instead look for a shorter version of that name: https://github.com/mcoughlin/gwemlightcurves/blob/master/gwemlightcurves/lightcurve_utils.py#L514

**Comment by sahiljhawar** [comment]
Ahh okay. What I read from the `PyMultiNest` [issue](https://github.com/JohannesBuchner/PyMultiNest/issues/115) is `post_equal_weights.dat` is created internally in MultiNest, so there's no way to shorten this or to increase the file name limit, base filename character limit in PyMultiNest is 100, however MultiNest increased it to 1000, but PyMultiNest author didn't do so to avoid code breakage. In another [issue](https://github.com/JohannesBuchner/PyMultiNest/issues/107), [author](suggested) to use temp folder. I'll try this and see if this works.

**Comment by tsunhopang** [comment]
The `tmp` folder only works if running without mpi.

That's why bilby (which is the backend for our sampling) would automatically make use of `tmp` if not run with mpi and switch if off once it is in mpi.

**Comment by sahiljhawar** [comment]
Maybe we can always do it in a two step process. The output directory is hardcoded in the code, maybe `temp` or `out`. And after analysis, move the contents to the given directory with base filename `--outdir`.

Or raise error when base filename is greater than 100 characters. And ask to rerun with shorter filename. To avoid wasting time in analysis when the finally it is going to fail.

**Comment by sahiljhawar** [comment]
Or maybe ship NMMA with it's own version of PyMultiNest with increased character limit, which will definitely be a overkill.

**Comment by tsunhopang** [comment]
Rasing the error sounds good to me

**Comment by sahiljhawar** [comment]
@tsunhopang Yes, Michael already merged the PR.

**Comment by sahiljhawar** [comment]
@mcoughlin Yes, you already merged the PR
