### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by mcoughlin** [nuclear-multimessenger-astronomy/nmma#15]
The weight of our dependencies makes installation something of a nightmare (including successful running of the CI). We need to at the very least make some dependencies optional.

**Comment by mcoughlin** [comment]
Related PR: https://github.com/bitranox/wrapt_timeout_decorator/pull/36

**Comment by tylerbarna** [comment]
Local installations on MacOS seem to be an issue going off experiences during ZTF Summer School

**Comment by tylerbarna** [comment]
is there an inconsistency in the requirements for nmma and parallel-bilby? doing a fresh install and getting an error with `pip install .` that goes:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
parallel-bilby 2.0.2 requires bilby-pipe>=1.0.7, but you have bilby-pipe 1.0.5 which is incompatible.`

installing `bilby-pipe==1.0.7` gives the following:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nmma 0.0.8 requires bilby-pipe==1.0.5, but you have bilby-pipe 1.0.7 which is incompatible.`

**Comment by mcoughlin** [comment]
@tylerbarna have you tried setting >= for bilby_pipe and see if we can allow for a more recent version?

**Comment by tsunhopang** [comment]
I am working on this dependency issue with @ninakuni , will keep you posted

**Comment by mcoughlin** [comment]
Closing this for now. Thanks for your improvements @tsunhopang
