### ISSUE TITLE
Remove additional NN layer between input and wide layer?

### ISSUE THREAD

**Issue by bfhealy** [nuclear-multimessenger-astronomy/nmma#151]
Between our NN's input layer and the wide (2048 neurons) layer, there is currently another layer that has the same shape as the input layer. I previously missed that this was an additional hidden layer, or I would have removed it:

https://github.com/nuclear-multimessenger-astronomy/nmma/blob/03d51ac48a80d69f54e72014a183e66e2c6a175b/nmma/em/training.py#L390

Training the same model using this updated architecture versus the current one seems to offer slight performance improvements, especially at early times; see the attached collapsar model runs comparing the current (top) and new (bottom) NN architectures. I can't make an argument for keeping this additional hidden layer (except the need to re-train any tf models and propagate this change through to existing results). 

Current:
![injection_AnBa2022_lightcurves_oldNN](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/42810347/ac113e01-cad2-4258-ae8b-a3cfee6edd77)

New:
![injection_AnBa2022_lightcurves_newNN](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/42810347/5c6618a2-ab20-4b2e-95e5-bbc2c43d6bdd)

**Comment by mcoughlin** [comment]
@bfhealy maybe also we should get in the habit of running the svdmodel_benchmark and comparing those? But yeah, it seems like we should upgrade it is better.

**Comment by bfhealy** [comment]
@mcoughlin Agreed about the benchmarks. I'll go ahead open a PR removing that layer from the NN.
