### ISSUE TITLE
Update installation Docs for pip

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#171]
**Feature Summary**
Update the documentation to reflect nmma now being installable via pip. Would be good to integrate the changes made to the structure of the installation docs in #105 as part of solving this issue

**Usage / behavior**
When looking at the installation docs, they would be updated

**Alternative Solutions**
Just updating the docs without adding the structure changes

**Implementation details**
Edit the docs file on installation and update it

**Additional context**
This is the relevant file in the docs: https://github.com/nuclear-multimessenger-astronomy/nmma/blob/main/doc/installation.md

**Comment by sahiljhawar** [comment]
Is `pip install nmma` a standalone command? As in, can be used without worrying about pbilby, multinest, etc?
