### ISSUE TITLE
AnBa2022 parameters

### ISSUE THREAD

**Issue by bfhealy** [nuclear-multimessenger-astronomy/nmma#177]
With recent changes to the `AnBa2022` parameters (using `log10_mtot` instead of `mtot`, etc.), there may be some remaining vestiges of the original parameters that affect benchmarking and light curve analysis. One example is how the code below takes the `log10` of the input parameters, which are now already in log-form.

https://github.com/nuclear-multimessenger-astronomy/nmma/blob/f9fce5a0cc056a1c47e035c3806aaf2ca7561b87/nmma/em/model_parameters.py#L24

When I comment the above `log10` lines, the benchmarking results for this model look much more reasonable than before.

It may also be helpful to update the `AnBa2022.prior` file to use the new log10 parameters. What do you think, @tsunhopang?

**Comment by tsunhopang** [comment]
I think that's a good idea. @ninakuni could u have the prior file updated after you have the model tested on the event?

**Comment by mcoughlin** [comment]
@tsunhopang @ninakuni Is this now resolved?

**Comment by tsunhopang** [comment]
yes it is resolved. And now the code can handle both log and unlogged ejecta mass with the model built with log or unlogged masses.
