### ISSUE TITLE
Change default page in docs to installation

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#182]
**Feature Summary**
change the default page from the quickstart to the installation instructions

**Alternative Solutions**
Have the default page be a basic welcome page with a button to proceed to installation

**Additional context**
This should also accompany an update to the structure of the installation docs, perhaps by making the installation issues a seperate page

**Comment by sahiljhawar** [comment]
https://github.com/nuclear-multimessenger-astronomy/nmma/blob/4355bc57d7f9e082ba6cc0b39756ea19e9dda277/doc/conf.py#L66

This should be changed to `installation.md`

**Comment by tylerbarna** [comment]
> This should be changed to `installation`?

either that or we just have a basic intro page (essentially the same content as the readme for the repo) as the index with a button at the bottom to proceed to the installation; for a new user, there should probably be a linear experience for: (1) navigating to the docs from the repo (2) being told how to install nmma and (3) running the quickstart commands to validate nmma has been installed correctly

**Comment by sahiljhawar** [comment]
Maybe someone who knows web dev can create a default landing page. I tried to change the default page in the #185 but it didn't work that way.

**Comment by mcoughlin** [comment]
@sahiljhawar @tylerbarna Is this now resolved?

**Comment by sahiljhawar** [comment]
Yes
