### ISSUE TITLE
light_curve_analysis for multiple models

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#214]
Please fill out relevant sections below; remove those that are unused.

**Feature Summary**
A function on top of the existing light_curve_analysis that allows for multiple models to be analyzed at once 

**Usage / behavior**
Call multi_model_analysis with the same arguments as light_curve_analysis, but including multiple models and priors in the arguments will result in analyses being executed for each model. Once all analyses are concluded, an optional plot flag will plot all of the model best fits together with the data.

**Alternative Solutions**
Could alter the behaviour of light_curve_analysis to have adding multiple models and priors to do what I described rather than doing a mix of the models, but I think the suggestion of another function would be better for compatibility

**Implementation details**
Additional command line function that just calls light_curve_analysis for each associated model and prior before a unique plotting feature to plot them all together onto one plot (with corner plots remaining separate)

**Additional context**
Would need to account for models taking different amounts of time to fit and also implement some type of cutoff to account for models that stall. Will also need to account for the potential of failed fits.

**Comment by sahiljhawar** [comment]
I think multi-model analysis already exists. I don’t exactly remember but somewhere @tsunhopang mentioned that the fluxes/luminosities add up if multiple models are being used at once.

**Comment by mcoughlin** [comment]
@sahiljhawar I think what @tylerbarna wants is a function that will loop over model configurations, and presumably compute odds ratios for you.

**Comment by sahiljhawar** [comment]
Hmm okay, maybe I understood it wrong.
