### ISSUE TITLE
LSST sampling fails for Me2017

### ISSUE THREAD

**Issue by ritwiksharma049** [nuclear-multimessenger-astronomy/nmma#24]
Running the command lines for Me2017 model with Rubin Sampling does not create **outdir** and **outdir/lc.csv** are not obtained.

1. nmma_create_injection --prior-file priors/Me2017.prior --eos-file example_files/eos/ALF2.dat --binary-type BNS --n-injection 100 --original-parameters --extension json

2. light_curve_analysis --model Me2017 --svd-path ./svdmodels --outdir outdir --label injection --prior priors/Me2017.prior --tmin 0.05 --tmax 20 --dt 0.01 --error-budget 1 --nlive 512 --Ebv-max 0 --injection ./injection.json --injection-num 0 --injection-outfile outdir/lc.csv --generation-seed 42 --filters u,g,r,i,z,y --plot --remove-nondetections --rubin-ToO --rubin-ToO-type BNS --injection-detection-limit 23.9,25.0,24.7,24.0,23.3,22.1

**Comment by mcoughlin** [comment]
Running these exact lines, I get in the output directory:

ls outdir
injection.log			lc.csv
injection_corner.png		lightcurves.png
injection_posterior_samples.dat	pm_injection
injection_result.json

**Comment by ritwiksharma049** [comment]
why ls outdir? did you mean cd outdir?

Also, 

injection.log: command not found

**Comment by ritwiksharma049** [comment]
The command lines in my case do not produce even the outdir directory. Probably something with my machine, which I am not sure of.
