### ISSUE TITLE
trigger-time flag setting

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#256]
**Describe the bug**
Currently, trigger-time is an optional flag for light_curve_analysis, but it's effectively a mandatory parameter in order for analysis to run. For example, for a lightcurve with an initial time of t=4000, not setting the trigger time will cause the log likelihood to always be negative infinity, which I suspect is due to the trigger time being set to something like t=0 if not specified

**To Reproduce**
1. generate an injection and lightcurve for any model
2. run light-curve-analysis without specifying trigger-time
3. see as your terminal is filled with low likelihood warnings

**Expected behavior**
lightcurve analysis should proceed regardless of whether or not the trigger time is specified. Trigger time should default to the first data point time, with the option of specifying a different time

**Platform information:**
 - NMMA version: all versions
 - Platform: all versions 

**Additional context**
This should be fixed by 
- [x] warning users that they have not set a trigger time
- [x] automatically setting the trigger time to be equal to the time of the first data point

Alternatively, we could modify the trigger-time behaviour in the backend to be relative to the start time of the lightcurve, which is how the tmin and tmax parameters work, but that would be a discussion to have with @mcoughlin, as I'm not sure how much modification that would require

**Comment by sahiljhawar** [comment]
Instead of raising warning, why not make it a required parameter?

**Comment by tylerbarna** [comment]
> Instead of raising warning, why not make it a required parameter?

I think the default use case is to set the trigger time as the first data point, so I believe it would make more sense to have the trigger time set automatically to be that with the optional choice to set a different trigger time

**Comment by sahiljhawar** [comment]
If I undestand it correctly, trigger time is set to the first data point if the data file is available else it defaults to the sampling tmin. In either cases a warning should be raised that trigger time not given and a default value will be used (based on previous)

**Comment by tylerbarna** [comment]
@sahiljhawar I believe the current behaviour is that the trigger time is set to 0 if the trigger time parameter isn't set, my previous comment was moreso regarding what the ideal implementation would be
