### ISSUE TITLE
Issue on page /gw_inference.html

### ISSUE THREAD

**Issue by prashantstar123** [nuclear-multimessenger-astronomy/nmma#306]
Hello All,
I am trying to run Inference of gravitational-wave signals, from the steps given in NMMA offical documentation , I am able to successfully generate **config.ini** file but when I am trying to run nmma-gw-analysis  locally on my  desktop by the command generated in folder **submit** in file "analysis_GW170817_0.sh" by command "mpirun nmma_gw_analysis outdir/data/GW170817_data_dump.pickle --nact 5 --n-check-point 10000 --label GW170817_0 --sampling-seed 878327 --outdir /home/prashant/nmma/outdir/result" , it is giving error  "**nmma_gw_analysis: error: unrecognised arguments: outdir/data/GW170817_data_dump.pickle**"
but when i do above same for "parallel_bilby_analysis" it is running without any error.
Please see the issue and I will be highly thankful if anyone Please help me
**Also i am attaching the supporting screenshots and files.**
![Screenshot from 2024-01-12 17-02-00](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/391abeb8-4008-4693-9cd2-5e5e71cc47dc)
![Screenshot from 2024-01-12 17-04-11](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/6d04929d-c1c1-419b-bffd-7f09414b253b)
![Screenshot from 2024-01-12 17-02-00](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/c4162a4b-50e2-478d-bda1-9a74bf756e21)
![Screenshot from 2024-01-12 17-01-29](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/46de84f6-2fe9-499f-8456-5bd3f3dcdbbe)
[config.txt](https://github.com/nuclear-multimessenger-astronomy/nmma/files/13918646/config.txt)

**Comment by mcoughlin** [comment]
@prashantstar123 https://github.com/nuclear-multimessenger-astronomy/nmma/blob/main/nmma/pbilby/parser/analysis.py#L14 I see the first argument as --data-dump. @tsunhopang @ninakuni Is the GW docs out of date? https://github.com/nuclear-multimessenger-astronomy/nmma/blob/main/doc/gw_inference.md

**Comment by tsunhopang** [comment]
Could you post the full error message here?

**Comment by mcoughlin** [comment]
@tsunhopang From above: mpirun nmma_gw_analysis outdir/data/GW170817_data_dump.pickle --nact 5 --n-check-point 10000 --label GW170817_0 --sampling-seed 878327 --outdir /home/prashant/nmma/outdir/result

Which I think is missing the --data-dump flag. However, that flag is not in the docs, as far as I can tell.

**Comment by tsunhopang** [comment]
No the flag is not needed, as we are using the same parser as the parallel_bilby. That why I want to check with the full error message and see

**Comment by tsunhopang** [comment]
I found the problematic commit https://github.com/nuclear-multimessenger-astronomy/nmma/commit/a43970b28ab38fa9ac846fecec839272d34a5f7d , let me have that change on --data-dump undone

**Comment by tsunhopang** [comment]
@prashantstar123, please try the latest version of nmma and see if it solves your problem

**Comment by prashantstar123** [comment]
no @tsunhopang the problem is still same the error is "nmma_gw_analysis: error: unrecognised
![Screenshot from 2024-01-13 10-08-46](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/436b7294-f827-40f7-a2c8-8c2ac29ba993)
![Screenshot from 2024-01-13 10-08-31](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/7a08395a-0aa5-4180-bedc-623d22f231ed)
 arguments: outdir/data/GW170817_data_dump.pickle" I have replaced the analysis.py with new one. Attaching the supporting screenshots

**Comment by tsunhopang** [comment]
@prashantstar123, may I ask what the git hash of nmma you are running? As I have the fix pushed and tested to be fine on git hash 997f3c508623e3f20872f7f6941a209165a0eba4
<img width="1805" alt="Screenshot 2024-01-13 at 09 34 26" src="https://github.com/nuclear-multimessenger-astronomy/nmma/assets/23866970/1198c9f7-f745-4cf0-b095-c6fe19982e28">

**Comment by prashantstar123** [comment]
@tsunhopang I am getting this
![Uploading Screenshot from 2024-01-13 14-21-01.png…]()

**Comment by prashantstar123** [comment]
@tsunhopang I am attaching screenshot of analysis.py that i am using
![Screenshot from 2024-01-13 14-24-34](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/cae34f0d-f8cd-4013-92e5-6b3384152869)

**Comment by tsunhopang** [comment]
I would suggest you to have nmma completely uninstalled from your env, (either with `pip uninstall nmma` or remove the package directory from the env) afterwards, reinstall nmma by running `pip install .` within the source directory

**Comment by prashantstar123** [comment]
@tsunhopang I have tried as you said now it is giving this error , attaching screenshot
![Screenshot from 2024-01-13 15-30-41](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/11cfa2dd-5f62-4f68-aca6-e84b06de98a1)

**Comment by tsunhopang** [comment]
I have reverted the changes, could you try with `--data-dump input.pickle` and see if it works? If it works, I will update the gw_inference.html accordingly

**Comment by prashantstar123** [comment]
@tsunhopang hey, Please if you dont mind could you explain in detail with step(if necesaary) what do you mean with above?
Also my ubuntu got crashed so i think now it will take time from my side

**Comment by tsunhopang** [comment]
so I have pushed some changes to nmma, in which you can reinstall nmma to have these changes installed in your env. After which, when you run the `nmma-gw-analysis`, run it with `nmma-gw-analysis --data-dump YOUR_INPUT.pickle --nlive 2048 ....`

**Comment by prashantstar123** [comment]
@tsunhopang ok thanku give me some time i will rewert you back

**Comment by prashantstar123** [comment]
![Screenshot from 2024-01-14 15-32-53](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/4767272c-a303-4f8c-be7b-77546ec170aa)
@tsunhopang I reinstalled everything, but it againg give me some new errors, Please look it into , i am attaching screenshots
strange part is if i run parallel_bilby_analysis, it runs without any error
![Screenshot from 2024-01-14 15-33-51](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/f8f51ac1-9b4b-4bae-9caf-b7fd8198bff9)
![Screenshot from 2024-01-14 15-33-13](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/90745170/47037bae-fd14-4004-a546-2831e61c98b2)

**Comment by tsunhopang** [comment]
can you also attach the config file and prior file used?

by "`parallel_bilby_analysis` works", do you mean the same config file works under `parallel_bilby_generation` and subsequent `parallel_bilby_analysis`?

**Comment by prashantstar123** [comment]
[config.txt](https://github.com/nuclear-multimessenger-astronomy/nmma/files/13931111/config.txt)
[GW170817_prior.txt](https://github.com/nuclear-multimessenger-astronomy/nmma/files/13931116/GW170817_prior.txt)
I mean to say that when i run example "**https://git.ligo.org/lscsoft/parallel_bilby/-/blob/master/examples/GW170817_IMRPhenomPv2_NRTidal/tutorial.ipynb**" from parallel_bilby documentation it is running. Thank you

**Comment by tsunhopang** [comment]
could you try without the distance marginalization turned on?

**Comment by prashantstar123** [comment]
@tsunhopang, thank you so much. It is running, but since I am running it on a local machine, I will monitor it for some more time to see if any errors occur. I will revert back to you. Thank you so much

**Comment by tsunhopang** [comment]
I have the doc updated under commits https://github.com/nuclear-multimessenger-astronomy/nmma/commit/a736a7f2fb3cd2bbabbeb5114de4cbda5347f629 and https://github.com/nuclear-multimessenger-astronomy/nmma/commit/c7db4bb9f11f4899a43cd7ac94fa879fa1b69745 , closing this issue.

@prashantstar123 in case there are other problem, please start a new issue
