### ISSUE TITLE
Filter naming consistency in make_lcs.py

### ISSUE THREAD

**Issue by bfhealy** [nuclear-multimessenger-astronomy/nmma#326]
The default filters in `make_lcs.py` are as follows:

https://github.com/nuclear-multimessenger-astronomy/nmma/blob/9431c3b906b211225545957b7cbda49db85baafa/tools/make_lcs.py#L15

Among these defaults, there are a some inconsistencies with sncosmo filter names that raise errors during training: 
- SDSS filter naming (should be e.g. `sdssu` instead of `sdss::u`)
- Swope2 filter naming (potential mapping: `swope2::y` -> `cspys`, `swope2::J` -> `cspjs`, `swope2::H` -> `csphs`)

Several grids I've worked with (e.g. Bu2019lm, Bu2022Ye) have come with the following filters:

`bessellux bessellb bessellv bessellr besselli sdssu ps1::g ps1::r ps1::i ps1::z ps1::y uvot::b uvot::u uvot::uvm2 uvot::uvw1 uvot::uvw2 uvot::v uvot::white atlasc atlaso 2massj 2massh 2massks ztfg ztfr ztfi`

Perhaps these filters (plus `ultrasat`) should instead be the defaults in `make_lcs.py`? @mcoughlin, I'd appreciate your thoughts.

**Comment by mcoughlin** [comment]
@bfhealy I agree. I even wonder if we should have a "default_filters" function that is callable from scripts in the app that simply returns this list?
