### ISSUE TITLE
Failing CI to Docker Hub / build (linux/arm64/v8)

### ISSUE THREAD

**Issue by sahiljhawar** [nuclear-multimessenger-astronomy/nmma#337]
@Theodlz Can you please look into this?

**Comment by bfhealy** [comment]
Attempted a fix with #339, but it didn't change the error we're getting.

**Comment by sahiljhawar** [comment]
@bfhealy The issue is related to `CFLAGS` on arm architecture, specifically due to these two flags `-mavx2` and `-msse2`. Numcodecs already pushed a fix [#40754](https://github.com/spack/spack/pull/40754). But due to internal dependecies in `ligo.skymap`

```
Collecting numcodecs>=0.10.0 (from zarr->reproject>=0.3.2->ligo.skymap->-r /requirements.txt)
```

`zarr` wants `numcodecs>=0.10.0` and it indeed gets a higher version but it is still low `0.12.1` which is really old and does not contain the fix. So, either we explicitly install recent `numcodecs` or ask `zarr` to update . I suggest that we try to install numcodecs explicitly. Also, this issue is something none of us arm Mac user faced and is restricted to arm Linux.

**Comment by bfhealy** [comment]
@sahiljhawar I see, thanks! I agree we should try to install numcodecs explicitly and see what happens from there.

**Comment by sahiljhawar** [comment]
Ahh no, I am sorry. I mixed up two different numcodecs issues. However the underlying reason is still the same.
