### ISSUE TITLE
Workflow for conda installation on Linux/MacOS

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#338]
**Feature Summary**
set up a workflow for pull requests intended to be used as versioned releases to validate that installing the package via conda

**Usage / behavior**
We would submit a PR with a proposed versioned release tag, which would trigger a specific github action that tests if the conda environment can be created (see: https://stackoverflow.com/questions/62325286/run-github-actions-when-pull-requests-have-a-specific-label)

**Implementation details**
Part of Github Workflow

**Additional context**
Result of some difficulties encountered at NMMA retreat; basic NMMA installation on Ubuntu was having some trouble

**Comment by sahiljhawar** [comment]
The issue you described is already fulfilled by conda nmma-feedstock.

**Comment by sahiljhawar** [comment]
@tylerbarna See here: https://github.com/nuclear-multimessenger-astronomy/nmma

**Comment by tylerbarna** [comment]
> @tylerbarna The issue you described is already fulfilled by conda nmma-feedstock.

Ah okay cool, did not realize
