### ISSUE TITLE
ImportError: cannot import name 'update_default_config' from 'astropy.config.configuration'

### ISSUE THREAD

**Issue by s-paramvir** [nuclear-multimessenger-astronomy/nmma#378]
**Describe the bug**
After correct installation and verification, running the lightcurve-analysis (also via mpi) does not initialize at all. 
The sncosmo/\__init.py file calls a configuration file from astropy, but the function seems to be deprecated. 

**To Reproduce**
1. Install according the procedure outlined in documentation. 
2. Run command: a similar command as the following via shell:
'mpiexec -np 20 lightcurve-analysis --model Bu2019lm,TrPi2018 --svd-path /nmma/svdmodels/ --interpolation-type tensorflow --outdir outdir --label GRB211211A --prior ./Bu2019lm_TrPi2018GRB211211A.prior --tmin 0.01 --tmax 10 --dt 0.01 --error-budget 1 --nlive 1024 --Ebv-max 0 --trigger-time 59559.54791666667 --data ./GRB211211A.txt --plot'
4. See error:   
File "/home/user/……./python3.10/site-packages/sncosmo/\__init.py", line 9, in module
    from astropy.config.configuration import update_default_config
ImportError: cannot import name 'update_default_config' from 'astropy.config.configuration' "/home/user/……./envs/NMMA_ENV_2/lib/python3.10/site-packages/astropy/config/configuration.py"

**Expected behavior**
Should initiate the Inference of multiple EM signals

**Platform information:**
NMMA version:  "0.2.0" and "0.2.1"
Ubuntu 22.04.4

**Comment by mcoughlin** [comment]
Please specify the versions of sncosmo and astropy you are using. I suspect your sncosmo is old given its an sncosmo error. I suggest importing sncosmo in a python prompt and let us know if you cannot get it fixed.

**Comment by s-paramvir** [comment]
I have these versions sncosmo = 2.9.0 and astropy = 6.0.0 (and also tried 6.1.0 or 6.1.1). Yes, I will try importing sncosmo and update you.

**Comment by s-paramvir** [comment]
Although, while checking further and assuming this to be an astropy error. I found that “update_default_config” function is deprecated from astropy versions>5.3.4. So I tested fixing the astropy==5.3.4. and could run lightcurve-analysis again.

**Comment by mcoughlin** [comment]
Thanks, I updated the minimum astropy in the requirements to reflect this.
