### ISSUE TITLE
valueError: unsupported pickle protocol: 5 

### ISSUE THREAD

**Issue by weizmannk** [nuclear-multimessenger-astronomy/nmma#44]
Somme thing goes wrong when we add ZTF flag  (--ztf-uncertainties --ztf-sampling --ztf-ToO 180)
, to [fitting](https://github.com/nuclear-multimessenger-astronomy/nmma/blob/main/doc/fitting.md.) observing scenarios data

I use **scikit-learn, : 1.0.1**  and **pandas : 1.3.5**

**Comment by weizmannk** [comment]
**The unsupported pickle protocol: 5 is is resolved** 
This  seems to be caused by the python versions, in my case python3.7.
It seems that nmma only supports python versions >=3.8.

> But be careful, python 3.10 causes in general  a lot problems on Linux systems,

>When I installed python 3.9 with nnma env , I got this error when running :
`import nmma.em.analysis `

ImportError: /home/wkiendrebeogo/anaconda3/envs/nmma/lib/python3.9/site-packages/numexpr/../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/wkiendrebeogo/anaconda3/envs/nmma/lib/python3.9/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-39-x86_64-linux-gnu.so)

- [ ] So in the meantime  it's better for those who use ubuntu 20.04 or linux ins general, to 
install nmma with **python3.8**

**Comment by mcoughlin** [comment]
@weizmannk can you open a PR on the docs saying this?

**Comment by weizmannk** [comment]
@mcoughlin  ok

**Comment by mcoughlin** [comment]
@weizmannk Can we close this?

**Comment by weizmannk** [comment]
@mcoughlin  yes, thanks.
