### ISSUE TITLE
plot flag file naming convention

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#53]
To my knowledge, the --plot flag in light_curve_analsysis currently outputs a file named lightcurves.png. To match the naming convention of the corner plots, output file name could be changed to use the label argument (ie "[--label]_lightcurves.png")

**Comment by mcoughlin** [comment]
@tylerbarna Is this now ready to close?

**Comment by tylerbarna** [comment]
@mcoughlin I believe so
