### ISSUE TITLE
Scipy =1.10 issue with bilby

### ISSUE THREAD

**Issue by weizmannk** [nuclear-multimessenger-astronomy/nmma#65]
scipy== 1.10.0 goes wrong with   bilby.gw.conversion  , specially  **bilby.gw.conversion.luminosity_distance_to_redshift**
 
 **ValueError: Use of `bounds` is incompatible with 'method=Brent'.**

 So we need to use the one between 1.7.1 and 1.9.3.

**Comment by mcoughlin** [comment]
@weizmannk Can you pin to 1.9.3?

**Comment by weizmannk** [comment]
it's done
