### ISSUE TITLE
Avoid error in create_svdmodel by excluding bolometric light curves

### ISSUE THREAD

**Issue by bfhealy** [nuclear-multimessenger-astronomy/nmma#88]
`create_svdmodel` raises an error when bolometric light curves are included in a directory that also contains filtered light curves. If we expect the names of light curve files to generally follow the format of the examples I've been using, we could avoid this error by modifying the `glob` [here](https://github.com/nuclear-multimessenger-astronomy/nmma/blob/722b02d10d95bf409da0aee1b01f4add4f32f7e1/nmma/em/create_svdmodel.py#L141) to exclude files ending with `_Lbol.dat` . This would not be useful if there is not a strict light curve file naming convention.

**Comment by mcoughlin** [comment]
Maybe an extra command line flag to ignore them?

**Comment by bfhealy** [comment]
That sounds good to me.
