### ISSUE TITLE
Bu2019lm svdmodel

### ISSUE THREAD

**Issue by tylerbarna** [nuclear-multimessenger-astronomy/nmma#91]
The current Bu2019lm.pkl file causes fitting kilonova to fail, which is fixed by removing it and adding the Bu2019lm_lbol.pkl and Bu2019lm_mag.pkl files to svdmodels, though these are too big to be included in the repo. Is there a reason why we still include the existing Bu2019lm.pkl file in the repo/why the kilonova fitting still points to the Bu2019lm.pkl file on a clean install?

**Comment by mcoughlin** [comment]
@tylerbarna Let's just delete the problematic pickle file then.

**Comment by mcoughlin** [comment]
@tylerbarna And add to the docs where to grab the correct ones..

**Comment by tylerbarna** [comment]
@mcoughlin yeah, I just wanted to check since I wasn't sure if the current pkl file was necessary for another tool that I don't interact with.

Are the existing svdmodel pkl files structured in such a way that we could just have a small script that breaks them up into chunks for the purposes of the repo but reconstructs them to their full size at the time of installation (with the full sized files just being added to the .gitignore)? Though that would add about 3.5 GB to the repo size depending on if they could be compressed further.

**Comment by mcoughlin** [comment]
I don't think it's that simple. I suggest someone train and test a new sklearn model and fix whatever in the code needs to be done to keep it at a normal size if that is desirable. To me, easier would be just a place where the files are placed and a documented set of wget commands can get them.
