### ISSUE TITLE
DockerHub

### ISSUE THREAD

**Issue by mcoughlin** [nuclear-multimessenger-astronomy/nmma#97]
https://github.com/nuclear-multimessenger-astronomy/nmma/actions/runs/5092341558/jobs/9153561323

Looks like we need to setup a username and password.

**Comment by Theodlz** [comment]
@mcoughlin can you make me a collaborator, or give me the permissions necessary to add those to the secrets please?

**Comment by mcoughlin** [comment]
@Theodlz done :)

**Comment by Theodlz** [comment]
Still can't see the settings. I think I need more power.
![image](https://github.com/nuclear-multimessenger-astronomy/nmma/assets/49785117/89fe9187-3383-4500-954a-23520752fbbf)

Otherwise, I can just send you the credentials on Slack as you prefer.

**Comment by Theodlz** [comment]
I see them 🤓

**Comment by Theodlz** [comment]
Seems like the credentials worked. Now we need a dockerfile 👀. Should we use the one I made on my repo?

**Comment by mcoughlin** [comment]
@Theodlz yes!

**Comment by Theodlz** [comment]
Will take care of it today!

**Comment by Theodlz** [comment]
Credentials added. Closing
